In [1]:
import numpy as np

In [2]:
v = [1,2,3,4,5]
a = np.array(v)

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
type(a)

numpy.ndarray

In [5]:
2 * a

array([ 2,  4,  6,  8, 10])

In [6]:
0.5 * a + 2

array([2.5, 3. , 3.5, 4. , 4.5])

In [8]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
b = np.arange(12).reshape((-1, 3))

In [10]:
a.mean()

3.0

In [17]:
%time a.mean()

CPU times: user 86 µs, sys: 0 ns, total: 86 µs
Wall time: 89.9 µs


3.0

In [15]:
b = list(a)
%time np.mean(b)

CPU times: user 96 µs, sys: 0 ns, total: 96 µs
Wall time: 101 µs


3.0

In [20]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
b.mean(axis=1)

array([ 1.,  4.,  7., 10.])

In [22]:
b.mean(axis=0)

array([4.5, 5.5, 6.5])

In [23]:
a = np.arange(15).reshape(5, 3)

In [24]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [27]:
import pandas as pd
index = pd.date_range('2021-7-1', periods=5, freq='B')


In [28]:
index

DatetimeIndex(['2021-07-01', '2021-07-02', '2021-07-05', '2021-07-06',
               '2021-07-07'],
              dtype='datetime64[ns]', freq='B')

In [29]:
df = pd.DataFrame(a, columns=list("abc"), index=index)

In [30]:
df

a   b   c
2021-07-01   0   1   2
2021-07-02   3   4   5
2021-07-05   6   7   8
2021-07-06   9  10  11
2021-07-07  12  13  14

In [33]:
df.sum()

a    30
b    35
c    40
dtype: int64